lab6/book_details/book_details/urls.py
# book_details/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('webapp.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

lab6/book_details/webapp/urls.py
# webapp/urls.py
from django.urls import path
from . import views

app_name = 'webapp'

urlpatterns = [
    path('', views.home, name='home'),
    path('metadata/', views.metadata, name='metadata'),
    path('reviews/', views.reviews, name='reviews'),
    path('publisher-info/', views.publisher_info, name='publisher_info'),
]

lab6/book_details/webapp/models.py
# webapp/models.py
from django.db import models

class Book(models.Model):
    title = models.CharField(max_length=200)
    cover_image = models.ImageField(upload_to='covers/')
    metadata = models.TextField()
    reviews = models.TextField()
    publisher_info = models.TextField()

    def __str__(self):
        return self.title

lab6/book_details/webapp/views.py
# webapp/views.py
from django.shortcuts import render, get_object_or_404
from .models import Book

def home(request):
    book = Book.objects.first()  # Get the first book (MVP)
    return render(request, 'webapp/home.html', {'book': book})

def metadata(request):
    book = Book.objects.first()
    return render(request, 'webapp/metadata.html', {'book': book})

def reviews(request):
    book = Book.objects.first()
    return render(request, 'webapp/reviews.html', {'book': book})

def publisher_info(request):
    book = Book.objects.first()
    return render(request, 'webapp/publisher_info.html', {'book': book})

lab6/book_details/webapp/templates/webapp/base.html
<!-- webapp/templates/webapp/base.html -->
<!DOCTYPE html>
<html>
<head>
    <title>Book Details</title>
</head>
<body>
    <nav>
        <a href="{% url 'webapp:home' %}">Home</a>
    </nav>
    {% block content %}
    {% endblock %}
</body>
</html>

lab6/book_details/webapp/templates/webapp/home.html
<!-- webapp/templates/webapp/home.html -->
{% extends 'webapp/base.html' %}

{% block content %}
    <h1>Book Details</h1>
    {% if book.cover_image %}
        <img src="{{ book.cover_image.url }}" alt="{{ book.title }} cover" width="200">
    {% endif %}
    <ul>
        <li><a href="{% url 'webapp:metadata' %}">Metadata</a></li>
        <li><a href="{% url 'webapp:reviews' %}">Reviews</a></li>
        <li><a href="{% url 'webapp:publisher_info' %}">Publisher Info</a></li>
    </ul>
{% endblock %}

lab6/book_details/webapp/templates/webapp/metadata.html
<!-- webapp/templates/webapp/metadata.html -->
{% extends 'webapp/base.html' %}

{% block content %}
    <h1>Book Metadata</h1>
    <p>{{ book.metadata }}</p>
{% endblock %}

lab6/book_details/webapp/templates/webapp/publisher_info.html
<!-- webapp/templates/webapp/publisher_info.html -->
{% extends 'webapp/base.html' %}

{% block content %}
    <h1>Publisher Information</h1>
    <p>{{ book.publisher_info }}</p>
{% endblock %}

lab6/book_details/webapp/templates/webapp/reviews.html
<!-- webapp/templates/webapp/reviews.html -->
{% extends 'webapp/base.html' %}

{% block content %}
    <h1>Book Reviews</h1>
    <p>{{ book.reviews }}</p>
{% endblock %}